services:
  surveybot:
    image: surveybot
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data/:/app/data
    configs:
      - source: bot_config
        target: /app/bot_cfg.json

configs:
  bot_config:
    file: ./bot_cfg.json
