services:
  surveybot:
    image: surveybot
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${PWD}/bot_cfg.json:/app/bot_cfg.json
      - ${PWD}/pers_state.json:/app/pers_state.json
      - ${PWD}/data/:/app/data
      - ${PWD}/ankets/:/app/ankets
